const fal9 = {
  id: "73ae8553-cc90-46e9-9a01-70a712493856",
  url:
    "https://lldev.thespacedevs.com/2.2.0/launch/73ae8553-cc90-46e9-9a01-70a712493856/",
  slug: "starship-sn15-10-km-flight",
  flightclub_url: null,
  r_spacex_api_id: null,
  name: "Starship SN15 | 10 km Flight",
  status: {
    id: 2,
    name: "To Be Determined",
    abbrev: "TBD",
    description:
      "Current date is a 'No Earlier Than' estimation based on unreliable or interpreted sources.",
  },
  last_updated: "2021-04-14T17:14:06Z",
  updates: [],
  net: "2021-04-20T00:00:00Z",
  window_end: "2021-04-20T00:00:00Z",
  window_start: "2021-04-20T00:00:00Z",
  probability: null,
  holdreason: "",
  failreason: "",
  hashtag: null,
  launch_service_provider: {
    id: 121,
    url: "https://lldev.thespacedevs.com/2.2.0/agencies/121/",
    name: "SpaceX",
    featured: true,
    type: "Commercial",
    country_code: "USA",
    abbrev: "SpX",
    description:
      "Space Exploration Technologies Corp., known as SpaceX, is an American aerospace manufacturer and space transport services company headquartered in Hawthorne, California. It was founded in 2002 by entrepreneur Elon Musk with the goal of reducing space transportation costs and enabling the colonization of Mars. SpaceX has many pads, on the East Coast of the US they own SLC-40 at Cape Canaveral and LC-39A at the Kennedy Space Center for their lower inclination launches. They also own SLC-4E at Vandenberg, California for their high inclination launches. Another site is also being developed at Boca Chica, Texas.",
    administrator: "CEO: Elon Musk",
    founding_year: "2002",
    launchers: "Falcon",
    spacecraft: "Dragon",
    launch_library_url: "https://launchlibrary.net/1.4/agency/121",
    total_launch_count: 130,
    consecutive_successful_launches: 1,
    successful_launches: 121,
    failed_launches: 9,
    pending_launches: 39,
    consecutive_successful_landings: 1,
    successful_landings: 86,
    failed_landings: 17,
    attempted_landings: 104,
    info_url: "http://www.spacex.com/",
    wiki_url: "http://en.wikipedia.org/wiki/SpaceX",
    logo_url:
      "https://spacelaunchnow-prod-east.nyc3.digitaloceanspaces.com/media/logo/spacex_logo_20191121063502.png",
    image_url:
      "https://spacelaunchnow-prod-east.nyc3.digitaloceanspaces.com/media/agency_images/spacex_image_20190207032501.jpeg",
    nation_url:
      "https://spacelaunchnow-prod-east.nyc3.digitaloceanspaces.com/media/agency_nation/spacex_nation_20190207032501.jpeg",
  },
  rocket: {
    id: 2852,
    configuration: {
      id: 207,
      url: "https://lldev.thespacedevs.com/2.2.0/config/launcher/207/",
      name: "Starship Prototype",
      description:
        "Prototype of SpaceX's Starship, a fully reusable second stage and space vehicle.",
      family: "Starship",
      full_name: "Starship Prototype",
      manufacturer: {
        id: 121,
        url: "https://lldev.thespacedevs.com/2.2.0/agencies/121/",
        name: "SpaceX",
        featured: true,
        type: "Commercial",
        country_code: "USA",
        abbrev: "SpX",
        description:
          "Space Exploration Technologies Corp., known as SpaceX, is an American aerospace manufacturer and space transport services company headquartered in Hawthorne, California. It was founded in 2002 by entrepreneur Elon Musk with the goal of reducing space transportation costs and enabling the colonization of Mars. SpaceX has many pads, on the East Coast of the US they own SLC-40 at Cape Canaveral and LC-39A at the Kennedy Space Center for their lower inclination launches. They also own SLC-4E at Vandenberg, California for their high inclination launches. Another site is also being developed at Boca Chica, Texas.",
        administrator: "CEO: Elon Musk",
        founding_year: "2002",
        launchers: "Falcon",
        spacecraft: "Dragon",
        launch_library_url: "https://launchlibrary.net/1.4/agency/121",
        total_launch_count: 130,
        consecutive_successful_launches: 1,
        successful_launches: 121,
        failed_launches: 9,
        pending_launches: 39,
        consecutive_successful_landings: 1,
        successful_landings: 86,
        failed_landings: 17,
        attempted_landings: 104,
        info_url: "http://www.spacex.com/",
        wiki_url: "http://en.wikipedia.org/wiki/SpaceX",
        logo_url:
          "https://spacelaunchnow-prod-east.nyc3.digitaloceanspaces.com/media/logo/spacex_logo_20191121063502.png",
        image_url:
          "https://spacelaunchnow-prod-east.nyc3.digitaloceanspaces.com/media/agency_images/spacex_image_20190207032501.jpeg",
        nation_url:
          "https://spacelaunchnow-prod-east.nyc3.digitaloceanspaces.com/media/agency_nation/spacex_nation_20190207032501.jpeg",
      },
      program: [
        {
          id: 1,
          url: "https://lldev.thespacedevs.com/2.2.0/program/1/",
          name: "SpaceX Starship",
          description:
            "The SpaceX Starship is a fully reusable super heavy-lift launch vehicle under development by SpaceX since 2012, as a self-funded private spaceflight project.  The second stage of the Starship — is designed as a long-duration cargo and passenger-carrying spacecraft. It is expected to be initially used without any booster stage at all, as part of an extensive development program to prove out launch-and-landing and iterate on a variety of design details, particularly with respect to the vehicle's atmospheric reentry.",
          agencies: [
            {
              id: 121,
              url: "https://lldev.thespacedevs.com/2.2.0/agencies/121/",
              name: "SpaceX",
              type: "Commercial",
            },
          ],
          image_url:
            "https://spacelaunchnow-prod-east.nyc3.digitaloceanspaces.com/media/program_images/spacex2520star_program_20201129204513.png",
          start_date: "2019-03-01T05:00:00Z",
          end_date: null,
          info_url: "https://www.spacex.com/vehicles/starship/",
          wiki_url: "https://en.wikipedia.org/wiki/SpaceX_Starship",
        },
      ],
      variant: "Prototype",
      alias: "",
      min_stage: 1,
      max_stage: 1,
      length: 50.0,
      diameter: 9.0,
      maiden_flight: "2019-07-26",
      launch_cost: null,
      launch_mass: 45,
      leo_capacity: null,
      gto_capacity: null,
      to_thrust: null,
      apogee: null,
      vehicle_range: null,
      image_url:
        "https://spacelaunchnow-prod-east.nyc3.digitaloceanspaces.com/media/launcher_images/starship_protot_image_20201211072211.png",
      info_url: "https://www.spacex.com/vehicles/starship/",
      wiki_url: "https://en.wikipedia.org/wiki/SpaceX_Starship",
      total_launch_count: 8,
      consecutive_successful_launches: 0,
      successful_launches: 5,
      failed_launches: 3,
      pending_launches: 1,
    },
    launcher_stage: [
      {
        id: 171,
        type: "Core",
        reused: false,
        launcher_flight_number: 1,
        launcher: {
          id: 94,
          url: "https://lldev.thespacedevs.com/2.2.0/launcher/94/",
          details:
            "Next Starship prototype built after SN11. It features hundreds of design improvements across structures, avionics, software and engine.",
          flight_proven: false,
          serial_number: "SN15",
          status: "active",
          image_url:
            "https://spacelaunchnow-prod-east.nyc3.digitaloceanspaces.com/media/launcher_core_images/none_image_20210409073338.jpeg",
          successful_landings: 0,
          attempted_landings: 0,
          flights: 0,
          last_launch_date: null,
          first_launch_date: null,
        },
        landing: {
          id: 202,
          attempt: true,
          success: null,
          description:
            "Starship SN15 will attempt to land back at the launch site after its high-altitude flight.",
          location: {
            id: 14,
            name: "SpaceX Starship Landing Pad",
            abbrev: "LZ",
            description:
              "This is the landing pad used for early Starship development flights.",
            location: {
              id: 143,
              url: "https://lldev.thespacedevs.com/2.2.0/location/143/",
              name: "SpaceX Space Launch Facility, TX, USA",
              country_code: "USA",
              map_image:
                "https://spacelaunchnow-prod-east.nyc3.digitaloceanspaces.com/media/launch_images/location_143_20200803142438.jpg",
              total_launch_count: 8,
              total_landing_count: 8,
            },
            successful_landings: 4,
          },
          type: {
            id: 2,
            name: "Return to Launch Site",
            abbrev: "RTLS",
            description:
              "A return to launch site usually means that after stage separation the booster flips and does a burn back towards the launch site, landing near where it initially launched from.",
          },
        },
        previous_flight_date: null,
        turn_around_time_days: null,
        previous_flight: null,
      },
    ],
    spacecraft_stage: null,
  },
  mission: {
    id: 1266,
    name: "10 km Flight",
    description:
      "The SN15 Starship prototype will perform a test flight similar to SN8 to SN11. It will launch up to an altitude of 10 km or 33,000 ft and do a belly flop maneuver followed by a controlled descent to the landing pad.",
    launch_designator: null,
    type: "Test Flight",
    orbit: {
      id: 15,
      name: "Suborbital",
      abbrev: "Sub",
    },
  },
  pad: {
    id: 111,
    url: "https://lldev.thespacedevs.com/2.2.0/pad/111/",
    agency_id: null,
    name: "Launch Pad A",
    info_url: null,
    wiki_url: "https://en.wikipedia.org/wiki/SpaceX_South_Texas_Launch_Site",
    map_url: "https://www.google.com/maps?q=25.997116+N,+97.15503099856647+W",
    latitude: "25.997116",
    longitude: "-97.15503099856647",
    location: {
      id: 143,
      url: "https://lldev.thespacedevs.com/2.2.0/location/143/",
      name: "SpaceX Space Launch Facility, TX, USA",
      country_code: "USA",
      map_image:
        "https://spacelaunchnow-prod-east.nyc3.digitaloceanspaces.com/media/launch_images/location_143_20200803142438.jpg",
      total_launch_count: 8,
      total_landing_count: 8,
    },
    map_image:
      "https://spacelaunchnow-prod-east.nyc3.digitaloceanspaces.com/media/launch_images/pad_111_20200803143229.jpg",
    total_launch_count: 6,
  },
  infoURLs: [],
  vidURLs: [
    {
      priority: 10,
      title: "Nerdle Cam 4K- SpaceX Starship Launch Facility",
      description:
        "THURSDAY 3/25/2021 Welcome to the LabPadre 24/7 Livestream! || Onsite weather provided by INITWeather.com || BOCA CHICA NEWS: GSE pressure test conducted Mar...",
      feature_image:
        "https://i.ytimg.com/vi/sTA0GTgFn5E/maxresdefault_live.jpg",
      url: "https://www.youtube.com/watch?v=sTA0GTgFn5E",
    },
  ],
  webcast_live: false,
  image:
    "https://spacelaunchnow-prod-east.nyc3.digitaloceanspaces.com/media/launch_images/starship2520sn_image_20210413205503.jpeg",
  infographic: null,
  program: [
    {
      id: 1,
      url: "https://lldev.thespacedevs.com/2.2.0/program/1/",
      name: "SpaceX Starship",
      description:
        "The SpaceX Starship is a fully reusable super heavy-lift launch vehicle under development by SpaceX since 2012, as a self-funded private spaceflight project.  The second stage of the Starship — is designed as a long-duration cargo and passenger-carrying spacecraft. It is expected to be initially used without any booster stage at all, as part of an extensive development program to prove out launch-and-landing and iterate on a variety of design details, particularly with respect to the vehicle's atmospheric reentry.",
      agencies: [
        {
          id: 121,
          url: "https://lldev.thespacedevs.com/2.2.0/agencies/121/",
          name: "SpaceX",
          type: "Commercial",
        },
      ],
      image_url:
        "https://spacelaunchnow-prod-east.nyc3.digitaloceanspaces.com/media/program_images/spacex2520star_program_20201129204513.png",
      start_date: "2019-03-01T05:00:00Z",
      end_date: null,
      info_url: "https://www.spacex.com/vehicles/starship/",
      wiki_url: "https://en.wikipedia.org/wiki/SpaceX_Starship",
    },
  ],
  orbital_launch_attempt_count: 1717,
  location_launch_attempt_count: 9,
  pad_launch_attempt_count: 7,
  agency_launch_attempt_count: 131,
  orbital_launch_attempt_count_year: 36,
  location_launch_attempt_count_year: 4,
  pad_launch_attempt_count_year: 2,
  agency_launch_attempt_count_year: 14,
};
